name: WaypointPlugin
version: 1.0
main: de.jaskerx.waypoints.main.Main
api-version: 1.17
author: JaskerX

commands:
   wps:
      description: Öffnet das Waypoint-Menü
   addWp:
      description: Fügt einen neuen Waypoint zum Menü hinzu
   addPrivateWp:
      description: Fügt einen neuen privaten Waypoint zum Menü hinzu
   delWp:
      description: Löscht den angegebenen Waypoint
   tpa:
      description: annehmen/ablehnen für Annehmen/Ablehnen der Anfrage